import os
from typing import Any

import render_machine.render_utils as render_utils
from plain2code_console import console
from render_machine.actions.base_action import BaseAction
from render_machine.failure_attribution import detect_layout_failure
from render_machine.render_context import RenderContext
from render_machine.render_types import RenderError

UNRECOVERABLE_ERROR_EXIT_CODES = [69]

LAYOUT_FAILURE_MESSAGE = (
    "Conformance test suites of this module could not be discovered or run together. "
    "This usually means the conformance tests were generated by an older version of the renderer - "
    "delete the module's conformance tests folder so they get regenerated on the next render. "
    "If the project uses a custom conformance tests script, make sure it runs all tests found "
    "under the folder it receives as its second argument, including tests in subfolders."
)


class RunConformanceTests(BaseAction):

    SUCCESSFUL_OUTCOME = "conformance_tests_passed"
    FAILED_OUTCOME = "conformance_tests_failed"
    UNRECOVERABLE_ERROR_OUTCOME = "unrecoverable_error_occurred"

    def execute(self, render_context: RenderContext, _previous_action_payload: Any | None):
        conformance_tests_script = os.path.normpath(render_context.conformance_tests_script)

        conformance_tests_folder_name = render_context.conformance_tests.get_module_suite_run_folder(
            render_context.module_name,
            render_context.required_modules,
            render_context.conformance_tests_running_context.current_testing_module_name,
        )

        console.info(
            f"Running conformance tests script {conformance_tests_script} "
            + f"for the test suite {conformance_tests_folder_name} "
            + f"of module {render_context.conformance_tests_running_context.current_testing_module_name}."
        )
        exit_code, conformance_tests_issue, conformance_tests_temp_log_file_path = render_utils.execute_script(
            conformance_tests_script,
            [render_context.build_folder, conformance_tests_folder_name],
            "Conformance Tests",
            frid=render_context.conformance_tests_running_context.current_testing_frid,
            module=render_context.conformance_tests_running_context.current_testing_module_name,
            timeout=render_context.test_script_timeout,
            stop_event=render_context.stop_event,
        )
        render_context.script_execution_history.latest_conformance_test_output_path = (
            conformance_tests_temp_log_file_path
        )
        render_context.script_execution_history.should_update_script_outputs = True

        if exit_code == 0:
            render_context.memory_manager.create_conformance_tests_memory(
                render_context, exit_code, conformance_tests_issue
            )
            # A passing whole-suite run of the module being rendered covers the FRID being
            # implemented, so its unresolved memory entries can be cleared.
            if (
                render_context.conformance_tests_running_context.current_testing_module_name
                == render_context.module_name
            ):
                render_context.memory_manager.delete_unresolved_memory_files()
            return self.SUCCESSFUL_OUTCOME, None

        if exit_code in UNRECOVERABLE_ERROR_EXIT_CODES:
            render_context.memory_manager.create_conformance_tests_memory(
                render_context, exit_code, conformance_tests_issue
            )
            console.error(conformance_tests_issue)
            return (
                self.UNRECOVERABLE_ERROR_OUTCOME,
                RenderError.encode(
                    message="Conformance tests script failed due to problems in the environment setup. Please check your environment or update the script for running conformance tests.",
                    error_type="ENVIRONMENT_ERROR",
                    script=conformance_tests_script,
                    issue=conformance_tests_issue,
                ).to_payload(),
            )

        if detect_layout_failure(conformance_tests_issue):
            console.error(conformance_tests_issue)
            return (
                self.UNRECOVERABLE_ERROR_OUTCOME,
                RenderError.encode(
                    message=LAYOUT_FAILURE_MESSAGE,
                    error_type="ENVIRONMENT_ERROR",
                    script=conformance_tests_script,
                    issue=conformance_tests_issue,
                ).to_payload(),
            )

        # Attribute the failure to a FRID (re-pointing the running context for the fix loop)
        # before creating memory, so the memory entry is keyed to the implicated FRID.
        conformance_tests_evidence = render_context.route_conformance_failure_to_frid(conformance_tests_issue)
        render_context.memory_manager.create_conformance_tests_memory(
            render_context, exit_code, conformance_tests_issue
        )

        return self.FAILED_OUTCOME, {"previous_conformance_tests_issue": conformance_tests_evidence}
