#!/bin/bash

set -euo pipefail

# Brand Colors (use exported colors if available, otherwise define them)
YELLOW="${YELLOW:-\033[38;2;224;255;110m}"
GREEN="${GREEN:-\033[38;2;121;252;150m}"
WHITE="${WHITE:-\033[38;2;255;255;255m}"
GRAY="${GRAY:-\033[38;2;128;128;128m}"
BOLD="${BOLD:-\033[1m}"
NC="${NC:-\033[0m}"

# Onboarding Step 1: Introduction to Plain
clear
echo ""
echo -e "  ${WHITE}${BOLD}***plain specification language intro${NC} (1/5)"
echo ""
echo -e "  ***plain is a language of spec-driven development that allows developers to express intent at any level of detail."
echo ""
echo -e "  Write specs in natural language extended with additional syntax based on markdown."
echo ""
echo -e "  A ***plain file has these key sections:"
echo ""
echo -e "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}***definitions***${NC}         - key concepts in your app  ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}***implementation reqs***${NC} - implementation details    ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}***test reqs***${NC}           - testing requirements      ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}***functional specs***${NC}    - what the app should do    ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  Let's see each section in a \"hello, world\" example."
echo ""
PROMPT=$(printf '%b' "  Press ${WHITE}[Enter]${NC} to continue...")
read -r -p "$PROMPT" < /dev/tty

# Onboarding Step 2: Definitions
clear
echo ""
echo -e "  ${WHITE}${BOLD}***plain specification language intro${NC} (2/5)"
echo ""
echo -e "  ${WHITE}${BOLD}DEFINITIONS${NC} - Definitions and descriptions of key concepts"
echo ""
echo -e "  Define ${WHITE}${BOLD}reusable concepts${NC} using the ${WHITE}${BOLD}:Concept:${NC} notation."
echo -e "  These become building blocks you can reference anywhere."
echo ""
echo -e "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}${BOLD}***definitions***${NC}                                     ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${WHITE}${BOLD}- :App: is a console application.${NC}                     ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***implementation reqs***${NC}                             ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :Implementation: should be in Python.${NC}               ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***test reqs***${NC}                                       ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :ConformanceTests: should use pytest.${NC}               ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***functional specs***${NC}                                ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :App: should display \"hello, world\".${NC}                ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${GREEN}▲${NC} The ${WHITE}:App:${NC} concept is defined once and used throughout the specs."
echo -e "    Concepts help keep your specs consistent and clear."
echo ""
PROMPT=$(printf '%b' "  Press ${WHITE}[Enter]${NC} to continue...")
read -r -p "$PROMPT" < /dev/tty

# Onboarding Step 3: Implementation & Test Reqs
clear
echo ""
echo -e "  ${WHITE}${BOLD}***plain specification language intro${NC} (3/5)"
echo ""
echo -e "  ${WHITE}${BOLD}IMPLEMENTATION & TEST REQS${NC} - How to implement and test"
echo ""
echo -e "  Specify ${WHITE}${BOLD}implementation details${NC} and ${WHITE}${BOLD}testing requirements${NC}."
echo -e "  This guides how the code should be generated and verified."
echo ""
echo -e "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***definitions***${NC}                                     ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :App: is a console application.${NC}                     ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}${BOLD}***implementation reqs***${NC}                             ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${WHITE}${BOLD}- :Implementation: should be in Python.${NC}               ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}${BOLD}***test reqs***${NC}                                       ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${WHITE}${BOLD}- :ConformanceTests: should use pytest.${NC}               ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***functional specs***${NC}                                ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :App: should display \"hello, world\".${NC}                ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${GREEN}▲${NC} ${WHITE}${BOLD}Implementation reqs${NC} define the language and frameworks."
echo -e "    ${WHITE}${BOLD}Test reqs${NC} ensure the generated code is verified."
echo ""
PROMPT=$(printf '%b' "  Press ${WHITE}[Enter]${NC} to continue...")
read -r -p "$PROMPT" < /dev/tty

# Onboarding Step 4: Functional Specification
clear
echo ""
echo -e "  ${WHITE}${BOLD}***plain specification language intro${NC} (4/5)"
echo ""
echo -e "  ${WHITE}${BOLD}FUNCTIONAL SPECS${NC} - What should the app do?"
echo ""
echo -e "  This is where you describe ${WHITE}what your app should do${NC},"
echo -e "  written in natural language. No code, just requirements."
echo ""
echo -e "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***definitions***${NC}                                     ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :App: is a console application.${NC}                     ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***implementation reqs***${NC}                             ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :Implementation: should be in Python.${NC}               ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}***test reqs***${NC}                                       ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GRAY}- :ConformanceTests: should use pytest.${NC}               ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${GREEN}${BOLD}***functional specs***${NC}                                ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}  ${WHITE}${BOLD}- :App: should display \"hello, world\".${NC}                ${GRAY}│${NC}"
echo -e "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
echo -e "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${GREEN}▲${NC} The ${WHITE}${BOLD}functional spec${NC} describes ${WHITE}${BOLD}what the app does${NC}."
echo -e "    Here, it simply displays \"hello, world\"."
echo ""
PROMPT=$(printf '%b' "  Press ${WHITE}[Enter]${NC} to continue...")
read -r -p "$PROMPT" < /dev/tty

# Onboarding Step 5: Rendering Code
clear
echo ""
echo -e "  ${WHITE}${BOLD}***plain specification language intro${NC} (5/5)"
echo ""
echo -e "  ${WHITE}${BOLD}RENDERING CODE${NC} - Generate your app"
echo ""
echo -e "  Once you have a ***plain file, generate code with:"
echo ""
echo -e "    ${WHITE}${BOLD}codeplain hello_world.plain${NC}"
echo ""
echo -e "  *codeplain will:"
echo ""
echo -e "    ${GRAY}1. Read your specification${NC}"
echo -e "    ${GRAY}2. Generate implementation code${NC}"
echo -e "    ${GRAY}3. Create and run tests to verify correctness${NC}"
echo -e "    ${GRAY}4. Output production-ready code${NC}"
echo ""
echo -e "  The generated code is guaranteed to match your specs"
echo -e "  and pass all defined tests."
echo ""
PROMPT=$(printf '%b' "  Press ${WHITE}[Enter]${NC} to finish...")
read -r -p "$PROMPT" < /dev/tty
