$ErrorActionPreference = 'Stop'

# Brand Colors (use exported colors if available, otherwise define them)
if (-not $env:YELLOW)     { $YELLOW      = "$([char]27)[38;2;224;255;110m" } else { $YELLOW      = $env:YELLOW }
if (-not $env:GREEN)      { $GREEN       = "$([char]27)[38;2;121;252;150m" } else { $GREEN       = $env:GREEN }
if (-not $env:WHITE)      { $WHITE       = "$([char]27)[38;2;255;255;255m" } else { $WHITE       = $env:WHITE }
if (-not $env:GRAY)       { $GRAY        = "$([char]27)[38;2;128;128;128m" } else { $GRAY        = $env:GRAY }
if (-not $env:BOLD)       { $BOLD        = "$([char]27)[1m"               } else { $BOLD        = $env:BOLD }
if (-not $env:NC)         { $NC          = "$([char]27)[0m"               } else { $NC          = $env:NC }

# Onboarding Step 1: Introduction to Plain
Clear-Host
Write-Host ""
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host "  ${YELLOW}${BOLD}***plain specification language intro${NC} - Step 1 of 5"
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host ""
Write-Host "  ***plain is a language of spec-driven development that allows developers to express intent at any level of detail."
Write-Host ""
Write-Host "  write specs in natural language extended with additional syntax based on markdown."
Write-Host ""
Write-Host "  render production-ready code with *codeplain."
Write-Host ""
Write-Host "  A ***plain file has these key sections:"
Write-Host ""
Write-Host "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}***definitions***${NC}      - key concepts in your app     ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}***implementation reqs***${NC}  - implementation details   ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}***test reqs***${NC}       - testing requirements          ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}***functional specs***${NC} - what the app should do       ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
Write-Host ""
Write-Host "  Let's see each section in a `"hello, world`" example."
Write-Host ""
Read-Host "  press [Enter] to continue..."

# Onboarding Step 2: Functional Specification
Clear-Host
Write-Host ""
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host "  ${YELLOW}${BOLD}***plain specification language intro${NC} - Step 2 of 5"
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host ""
Write-Host "  ${WHITE}${BOLD}FUNCTIONAL SPECS${NC} - what should the app do?"
Write-Host ""
Write-Host "  This is where you describe ${GREEN}what your app should do${NC},"
Write-Host "  written in natural language. No code, just requirements."
Write-Host ""
Write-Host "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***definitions***${NC}                                     ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :App: is a console application.${NC}                     ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***implementation reqs***${NC}                             ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :Implementation: should be in Python.${NC}               ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***test reqs***${NC}                                       ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :ConformanceTests: should use pytest.${NC}               ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}${BOLD}***functional specs***${NC}                                ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GREEN}${BOLD}- :App: should display `"hello, world`".${NC}                ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
Write-Host ""
Write-Host "  ${GREEN}▲${NC} The ${YELLOW}functional spec${NC} describes ${GREEN}what${NC} the app does."
Write-Host "    Here, it simply displays `"hello, world`"."
Write-Host ""
Read-Host "  press [Enter] to continue..."

# Onboarding Step 3: Definitions
Clear-Host
Write-Host ""
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host "  ${YELLOW}${BOLD}***plain specification language intro${NC} - Step 3 of 5"
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host ""
Write-Host "  ${WHITE}${BOLD}DEFINITIONS${NC} - definitions and descriptions of key concepts"
Write-Host ""
Write-Host "  Define ${GREEN}reusable concepts${NC} using the ${YELLOW}:Concept:${NC} notation."
Write-Host "  These become building blocks you can reference anywhere."
Write-Host ""
Write-Host "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}${BOLD}***definitions***${NC}                                     ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GREEN}${BOLD}- :App: is a console application.${NC}                     ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***implementation reqs***${NC}                             ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :Implementation: should be in Python.${NC}               ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***test reqs***${NC}                                       ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :ConformanceTests: should use pytest.${NC}               ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***functional specs***${NC}                                ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :App: should display `"hello, world`".${NC}                ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
Write-Host ""
Write-Host "  ${GREEN}▲${NC} The ${YELLOW}:App:${NC} concept is defined once and used throughout the specs."
Write-Host "    Concepts help keep your specs consistent and clear."
Write-Host ""
Read-Host "  press [Enter] to continue..."

# Onboarding Step 4: Implementation & Test Reqs
Clear-Host
Write-Host ""
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host "  ${YELLOW}${BOLD}***plain specification language intro${NC} - Step 4 of 5"
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host ""
Write-Host "  ${WHITE}${BOLD}IMPLEMENTATION & TEST REQS${NC} - how to implement and test"
Write-Host ""
Write-Host "  Specify ${GREEN}implementation details${NC} and ${GREEN}testing requirements${NC}."
Write-Host "  This guides how the code should be generated and verified."
Write-Host ""
Write-Host "${GRAY}  ┌────────────────────────────────────────────────────────┐${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***definitions***${NC}                                     ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :App: is a console application.${NC}                     ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}${BOLD}***implementation reqs***${NC}                             ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GREEN}${BOLD}- :Implementation: should be in Python.${NC}               ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${YELLOW}${BOLD}***test reqs***${NC}                                       ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GREEN}${BOLD}- :ConformanceTests: should use pytest.${NC}               ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}***functional specs***${NC}                                ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}  ${GRAY}- :App: should display `"hello, world`".${NC}                ${GRAY}│${NC}"
Write-Host "${GRAY}  │${NC}                                                        ${GRAY}│${NC}"
Write-Host "${GRAY}  └────────────────────────────────────────────────────────┘${NC}"
Write-Host ""
Write-Host "  ${GREEN}▲${NC} ${YELLOW}Implementation reqs${NC} define the language and frameworks."
Write-Host "    ${YELLOW}Test reqs${NC} ensure the generated code is verified."
Write-Host ""
Read-Host "  press [Enter] to continue..."

# Onboarding Step 5: Rendering Code
Clear-Host
Write-Host ""
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host "  ${YELLOW}${BOLD}***plain specification language intro${NC} - Step 5 of 5"
Write-Host "${GRAY}─────────────────────────────────────────────────────────${NC}"
Write-Host ""
Write-Host "  ${WHITE}${BOLD}RENDERING CODE${NC} - generate your app"
Write-Host ""
Write-Host "  Once you have a Plain file, generate code with:"
Write-Host ""
Write-Host "    ${YELLOW}${BOLD}codeplain hello_world.plain${NC}"
Write-Host ""
Write-Host "  *codeplain will:"
Write-Host ""
Write-Host "    ${GREEN}1.${NC} Read your specification"
Write-Host "    ${GREEN}2.${NC} Generate implementation code"
Write-Host "    ${GREEN}3.${NC} Create and run tests to verify correctness"
Write-Host "    ${GREEN}4.${NC} Output production-ready code"
Write-Host ""
Write-Host "  The generated code is guaranteed to match your specs"
Write-Host "  and pass all defined tests."
Write-Host ""
Read-Host "  press [Enter] to finish..."
